// Generated by CoffeeScript 1.12.7
(function() {
  $(function() {
    var a;
    console.log('home');
    a = 'aaa';
    Cs.log('kkk ASDF A');
    return alert(Str.hasStr(a, ''));
  });

}).call(this);

//# sourceMappingURL=home.js.map
