// Generated by CoffeeScript 2.5.1
(function() {
  window.b = function(o) {
    return console.log(o);
  };

  b.str = {
    /** # 문자열에 문자가 있는지 판별*/
    hasStr: function(full_str, keyword) {
      return full_str.indexOf(keyword) > -1;
    }
  };

}).call(this);

//# sourceMappingURL=b-js.js.map
