// Generated by CoffeeScript 1.12.7

/*


window.Str2 = {
  a: 'd'
  
  hasStr: (full_str, keyword) ->
    
    full_str.indexOf(keyword)> -1
 */

(function() {


}).call(this);

//# sourceMappingURL=Str.js.map
